# Generated by Django 4.0.3 on 2022-03-29 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_graph_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
