# Generated by Django 4.0.3 on 2022-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_remove_graph_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
