# Generated by Django 4.0.3 on 2022-04-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='p_tags',
            field=models.ManyToManyField(to='graph.tag'),
        ),
    ]
