# Generated by Django 4.0.3 on 2022-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_tag_graph_p_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='p_tags',
            field=models.ManyToManyField(blank=True, to='graph.tag'),
        ),
    ]
