# Generated by Django 4.0.3 on 2022-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_alter_graph_p_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='tags',
            field=models.CharField(
                blank=True, default='', max_length=2000, null=True),
        ),
    ]
