# Generated by Django 4.0.3 on 2022-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_alter_graph_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.TextField(
                blank=True, default='[{"id":"l1g63q47","type":"Task","width":125,"height":75,"x":255,"y":90,"name":"start"}]', null=True),
        ),
    ]
