# Generated by Django 4.0.3 on 2022-04-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_graph_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='tags',
            field=models.CharField(
                blank=True, default='new', max_length=2000, null=True),
        ),
    ]
